In [1]:
!pip install keras

In [2]:
!pip install opencv-python

In [3]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers,Sequential
from keras.layers import Conv2D,MaxPooling2D,Dense,Dropout,Flatten,Input
import pandas as pd
import numpy as np
import os
import cv2 as cv

In [4]:
cv.imread(r"C:\Users\vidya\Downloads\train\dogs\dog_92.jpg")

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [5]:
path=r"C:\Users\vidya\Downloads\train"

In [6]:
ct=["dogs","cats"]
ct.index("cats")

1

In [1]:
Data=[]
for i in ct:
    print(os.path.join(path,i))
    A=os.path.join(path,i)
    for j in os.listdir(A):
        #print(j)
        #print(os.path.join(A,j))
        B=os.path.join(A,j)
        img=cv.imread(B)
        img1=cv.resize(img,(150,150))
        labels=ct.index(i)
        Data.append([img1,labels])

NameError: name 'ct' is not defined

In [8]:
len(Data)

557

In [9]:
Data[400]

[array([[[202, 191, 184],
         [216, 204, 188],
         [239, 228, 220],
         ...,
         [106, 122, 149],
         [103, 118, 144],
         [ 91, 111, 136]],
 
        [[224, 213, 205],
         [195, 186, 173],
         [211, 201, 191],
         ...,
         [104, 121, 147],
         [105, 120, 146],
         [ 96, 116, 141]],
 
        [[220, 208, 198],
         [221, 214, 204],
         [215, 206, 193],
         ...,
         [103, 120, 146],
         [106, 121, 147],
         [ 96, 116, 141]],
 
        ...,
 
        [[144, 148, 159],
         [149, 153, 164],
         [139, 147, 160],
         ...,
         [171, 180, 189],
         [171, 175, 186],
         [157, 161, 172]],
 
        [[145, 152, 161],
         [140, 150, 163],
         [139, 146, 161],
         ...,
         [168, 180, 186],
         [170, 180, 190],
         [158, 168, 178]],
 
        [[141, 148, 157],
         [140, 149, 162],
         [141, 148, 163],
         ...,
         [165, 177, 183],
  

In [10]:
Data[400][0]

array([[[202, 191, 184],
        [216, 204, 188],
        [239, 228, 220],
        ...,
        [106, 122, 149],
        [103, 118, 144],
        [ 91, 111, 136]],

       [[224, 213, 205],
        [195, 186, 173],
        [211, 201, 191],
        ...,
        [104, 121, 147],
        [105, 120, 146],
        [ 96, 116, 141]],

       [[220, 208, 198],
        [221, 214, 204],
        [215, 206, 193],
        ...,
        [103, 120, 146],
        [106, 121, 147],
        [ 96, 116, 141]],

       ...,

       [[144, 148, 159],
        [149, 153, 164],
        [139, 147, 160],
        ...,
        [171, 180, 189],
        [171, 175, 186],
        [157, 161, 172]],

       [[145, 152, 161],
        [140, 150, 163],
        [139, 146, 161],
        ...,
        [168, 180, 186],
        [170, 180, 190],
        [158, 168, 178]],

       [[141, 148, 157],
        [140, 149, 162],
        [141, 148, 163],
        ...,
        [165, 177, 183],
        [166, 176, 186],
        [166, 176, 186]]

In [11]:
import random
random.shuffle(Data)

In [12]:
Data[1][1]

1

In [13]:
F=[]
T=[]

for i,j in Data:
    F.append(i)
    T.append(j)

In [14]:
F

[array([[[ 64,  80,  73],
         [ 63,  81,  73],
         [ 60,  78,  71],
         ...,
         [ 61,  93,  74],
         [ 59,  86,  86],
         [ 59,  81,  93]],
 
        [[ 62,  78,  72],
         [ 61,  79,  73],
         [ 59,  77,  70],
         ...,
         [ 61,  93,  75],
         [ 60,  86,  86],
         [ 59,  81,  93]],
 
        [[ 60,  75,  71],
         [ 59,  76,  72],
         [ 56,  74,  68],
         ...,
         [ 62,  94,  77],
         [ 61,  87,  88],
         [ 61,  82,  94]],
 
        ...,
 
        [[138, 129, 117],
         [142, 132, 121],
         [143, 134, 122],
         ...,
         [123, 157, 203],
         [118, 152, 198],
         [121, 155, 201]],
 
        [[137, 127, 117],
         [143, 133, 123],
         [147, 137, 127],
         ...,
         [122, 156, 202],
         [117, 151, 197],
         [123, 157, 203]],
 
        [[136, 126, 116],
         [144, 134, 124],
         [150, 139, 130],
         ...,
         [119, 152, 198],
  

In [15]:
F=np.array(F) #faster maths
T=np.array(T)

In [16]:
F.dtype

dtype('uint8')

In [17]:
F=F/255.

In [18]:
F

array([[[[0.25098039, 0.31372549, 0.28627451],
         [0.24705882, 0.31764706, 0.28627451],
         [0.23529412, 0.30588235, 0.27843137],
         ...,
         [0.23921569, 0.36470588, 0.29019608],
         [0.23137255, 0.3372549 , 0.3372549 ],
         [0.23137255, 0.31764706, 0.36470588]],

        [[0.24313725, 0.30588235, 0.28235294],
         [0.23921569, 0.30980392, 0.28627451],
         [0.23137255, 0.30196078, 0.2745098 ],
         ...,
         [0.23921569, 0.36470588, 0.29411765],
         [0.23529412, 0.3372549 , 0.3372549 ],
         [0.23137255, 0.31764706, 0.36470588]],

        [[0.23529412, 0.29411765, 0.27843137],
         [0.23137255, 0.29803922, 0.28235294],
         [0.21960784, 0.29019608, 0.26666667],
         ...,
         [0.24313725, 0.36862745, 0.30196078],
         [0.23921569, 0.34117647, 0.34509804],
         [0.23921569, 0.32156863, 0.36862745]],

        ...,

        [[0.54117647, 0.50588235, 0.45882353],
         [0.55686275, 0.51764706, 0.4745098 ]

In [19]:
F.shape #557 images,150 height,150 width,3 channels RGB

(557, 150, 150, 3)

In [34]:
model=Sequential()
model.add(Conv2D(80,(3,3),activation='relu'))
model.add(MaxPooling2D((2,2),strides=(1,1)))
model.add(Conv2D(60,(3,3),activation='relu'))
model.add(MaxPooling2D((2,2)))
model.add(Conv2D(40,(3,3),activation='relu'))
model.add(MaxPooling2D((2,2)))

model.add(Flatten())

model.add(Dense(50,input_shape=(150,150,3),activation='relu'))
model.add(Dense(30,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [36]:
model.compile(optimizer='adam',
             loss='binary_crossentropy',
             metrics=['accuracy'])

In [38]:
model.fit(F,T,epochs=1,validation_split=0.15)

15/15 ━━━━━━━━━━━━━━━━━━━━ 272s 17s/step - accuracy: 0.4814 - loss: 0.7080 - val_accuracy: 0.5000 - val_loss: 0.6994


In [49]:
#TE=r"C:\Users\RAHUL PATIL\Downloads\archive (10)\train\dogs\dog_234.jpg"
TE=r"C:\Users\vidya\Downloads\train\dogs\dog_50.jpg"
P=cv.imread(TE)
P=cv.resize(P,(150,150))
P=P/255
P=P.reshape(1,150,150,3)

In [53]:
P

array([[[[0.24705882, 0.32941176, 0.50588235],
         [0.10980392, 0.22745098, 0.40392157],
         [0.18823529, 0.34509804, 0.53333333],
         ...,
         [0.00392157, 0.01176471, 0.01176471],
         [0.00784314, 0.01568627, 0.01568627],
         [0.00392157, 0.01176471, 0.01176471]],

        [[0.2745098 , 0.34901961, 0.51372549],
         [0.10196078, 0.21960784, 0.38823529],
         [0.18431373, 0.3372549 , 0.51372549],
         ...,
         [0.00392157, 0.01176471, 0.01176471],
         [0.00784314, 0.01568627, 0.01568627],
         [0.00392157, 0.01176471, 0.01176471]],

        [[0.2745098 , 0.36078431, 0.50980392],
         [0.1254902 , 0.23137255, 0.39215686],
         [0.17647059, 0.32156863, 0.48627451],
         ...,
         [0.00392157, 0.01176471, 0.01176471],
         [0.00784314, 0.01568627, 0.01568627],
         [0.00392157, 0.01176471, 0.01176471]],

        ...,

        [[0.09411765, 0.0627451 , 0.01960784],
         [0.08627451, 0.05490196, 0.01568627]

In [56]:
#plt.imshow(P)

In [58]:
pred=model.predict(P)
pred[0][0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 578ms/step


0.4367174

In [60]:
if pred[0][0]<=0.5:
    print( 'its a Dog')
else:
    print( 'its a Cat')

its a Dog
